//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int SanPhamID { get; set; }
        public string TenSanPham { get; set; }
        public decimal Gia { get; set; }
        public Nullable<decimal> GiaGiam { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public string Loai { get; set; }
        public Nullable<int> GiamGia { get; set; }
    }
}
